# Generated by Django 3.0.8 on 2020-07-15 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_auto_20200715_2258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='username',
            new_name='name',
        ),
    ]
