# Generated by Django 3.1 on 2020-12-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sepsisAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('NO_SEPSIS', 'NO_SEPSIS'), ('SEPSIS_PREDICTED', 'SEPSIS_PREDICTED'), ('SEVERE_SEPSIS', 'SEVERE_SEPSIS'), ('SEPTIC_SHOCK', 'SEPTIC_SHOCK'), ('CURED', 'CURED')], default='NO_SEPSIS', max_length=20),
        ),
    ]
