# Generated by Django 3.1 on 2020-12-13 16:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sepsisAPI', '0002_patient_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='grp_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
